# Generated by Django 6.0 on 2026-01-02 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('review', 'W przeglądzie'), ('approval', 'Oczekuje na zatwierdzenie'), ('published', 'Opublikowany'), ('archived', 'Zarchiwizowany')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
        migrations.CreateModel(
            name='DocumentISOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('primary', 'Realizuje głównie'), ('supports', 'Wspiera realizację'), ('related', 'Powiązany')], default='primary', max_length=20, verbose_name='Typ powiązania')),
                ('section_reference', models.CharField(blank=True, help_text='Która sekcja/rozdział dokumentu odnosi się do wymagania', max_length=255, verbose_name='Sekcja dokumentu')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_iso_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_mappings', to='documents.document', verbose_name='Dokument')),
                ('iso_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_mappings', to='dictionary.isorequirement', verbose_name='Wymaganie ISO')),
            ],
            options={
                'verbose_name': 'Powiązanie dokument-ISO',
                'verbose_name_plural': 'Powiązania dokument-ISO',
                'ordering': ['iso_requirement__iso_id'],
                'unique_together': {('document', 'iso_requirement')},
            },
        ),
    ]
