# Generated by Django 5.2.8 on 2026-02-10 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_designation(apps, schema_editor):
    """Nadaj unikalny designation istniejącym dokumentom"""
    Document = apps.get_model('documents', 'Document')
    for i, doc in enumerate(Document.objects.all(), start=1):
        doc.designation = f'DOC-{i:03d}'
        doc.save(update_fields=['designation'])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_document_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log dokumentu', 'verbose_name_plural': 'Logi dokumentów'},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wersja dokumentu', 'verbose_name_plural': 'Wersje dokumentów'},
        ),
        # Krok 1: dodaj designation bez unique
        migrations.AddField(
            model_name='document',
            name='designation',
            field=models.CharField(default='', help_text='Unikalne oznaczenie dokumentu, np. POL-001, PROC-003', max_length=50, verbose_name='Oznaczenie'),
            preserve_default=False,
        ),
        # Krok 2: wypełnij istniejące rekordy unikalnymi wartościami
        migrations.RunPython(populate_designation, migrations.RunPython.noop),
        # Krok 3: dodaj constraint unique
        migrations.AlterField(
            model_name='document',
            name='designation',
            field=models.CharField(help_text='Unikalne oznaczenie dokumentu, np. POL-001, PROC-003', max_length=50, unique=True, verbose_name='Oznaczenie'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('policy', 'Polityka'), ('procedure', 'Procedura'), ('instruction', 'Instrukcja'), ('regulation', 'Regulamin'), ('plan', 'Plan'), ('report', 'Raport'), ('record', 'Zapis'), ('other', 'Inny')], default='other', max_length=20, verbose_name='Rodzaj dokumentu'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Oznacza wersję jako aktualnie obowiązującą', verbose_name='Wersja obowiązująca'),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='action',
            field=models.CharField(choices=[('created', 'Utworzono'), ('updated', 'Zaktualizowano'), ('status_changed', 'Zmieniono status'), ('version_added', 'Dodano wersję'), ('version_set_current', 'Ustawiono wersję obowiązującą'), ('access_granted', 'Nadano dostęp'), ('access_revoked', 'Cofnięto dostęp'), ('iso_linked', 'Powiązano z ISO'), ('iso_unlinked', 'Usunięto powiązanie ISO'), ('acknowledged', 'Potwierdzono zapoznanie')], max_length=30, verbose_name='Akcja'),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.document', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Czas'),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='change_description',
            field=models.TextField(blank=True, verbose_name='Opis zmian'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utworzył'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_number',
            field=models.CharField(max_length=20, verbose_name='Numer wersji'),
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'Podgląd'), ('edit', 'Edycja'), ('manage', 'Zarządzanie')], default='view', max_length=10, verbose_name='Poziom dostępu')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data nadania')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='documents.document', verbose_name='Dokument')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_access', to=settings.AUTH_USER_MODEL, verbose_name='Nadał')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dostęp do dokumentu',
                'verbose_name_plural': 'Dostępy do dokumentów',
                'ordering': ['document', 'user'],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zapoznania')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='documents.document', verbose_name='Dokument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentversion', verbose_name='Wersja dokumentu')),
            ],
            options={
                'verbose_name': 'Potwierdzenie zapoznania',
                'verbose_name_plural': 'Potwierdzenia zapoznań',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('document', 'user', 'version')},
            },
        ),
    ]
