# Generated by Django 5.2.8 on 2026-02-10 22:51

import django.db.models.deletion
from django.db import migrations, models


def clear_document_access(apps, schema_editor):
    """Wyczyść istniejące wpisy DocumentAccess - nie da się ich przenieść na grupy"""
    DocumentAccess = apps.get_model('documents', 'DocumentAccess')
    DocumentAccess.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_load_system_permissions'),
        ('documents', '0003_alter_documentlog_options_and_more'),
    ]

    operations = [
        # 1. Usuń stary unique_together (document, user)
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together=set(),
        ),
        # 2. Wyczyść istniejące wpisy — nie da się zmapować user→group automatycznie
        migrations.RunPython(clear_document_access, migrations.RunPython.noop),
        # 3. Dodaj nowe pole permission_group
        migrations.AddField(
            model_name='documentaccess',
            name='permission_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to='core.permissiongroup', verbose_name='Grupa uprawnień'),
            preserve_default=False,
        ),
        # 4. Usuń stare pole user
        migrations.RemoveField(
            model_name='documentaccess',
            name='user',
        ),
        # 5. Ustaw nowy unique_together i opcje modelu
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together={('document', 'permission_group')},
        ),
        migrations.AlterModelOptions(
            name='documentaccess',
            options={'ordering': ['document', 'permission_group'], 'verbose_name': 'Dostęp do dokumentu', 'verbose_name_plural': 'Dostępy do dokumentów'},
        ),
    ]
