# Generated by Django 5.2.8 on 2026-02-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_remove_asset_custodian_remove_asset_inventory_number_and_more'),
        ('core', '0008_load_system_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Temat')),
                ('description', models.TextField(verbose_name='Opis incydentu')),
                ('occurred_at', models.DateTimeField(verbose_name='Data i czas wystąpienia')),
                ('circumstances', models.TextField(help_text='Opis okoliczności w jakich doszło do incydentu', verbose_name='Okoliczności')),
                ('status', models.CharField(choices=[('reported', 'Zgłoszony'), ('analysis', 'Analiza'), ('response', 'Reakcja'), ('action', 'Działanie'), ('closed', 'Zakończony')], default='reported', max_length=20, verbose_name='Status')),
                ('is_serious', models.BooleanField(default=False, verbose_name='Poważny incydent')),
                ('involves_personal_data', models.BooleanField(default=False, verbose_name='Dotyczy danych osobowych')),
                ('severity', models.CharField(blank=True, choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], max_length=20, null=True, verbose_name='Klasyfikacja')),
                ('category', models.CharField(blank=True, choices=[('malware', 'Złośliwe oprogramowanie'), ('phishing', 'Phishing'), ('unauthorized_access', 'Nieautoryzowany dostęp'), ('data_leak', 'Wyciek danych'), ('hardware_failure', 'Awaria sprzętu'), ('software_failure', 'Awaria oprogramowania'), ('human_error', 'Błąd ludzki'), ('physical_security', 'Bezpieczeństwo fizyczne'), ('other', 'Inny')], max_length=30, null=True, verbose_name='Kategoria')),
                ('analysis_notes', models.TextField(blank=True, verbose_name='Notatki z analizy')),
                ('response_actions', models.TextField(blank=True, help_text='Jakie akcje zostały podjęte w reakcji na incydent', verbose_name='Podjęte działania')),
                ('response_notes', models.TextField(blank=True, verbose_name='Notatki z reakcji')),
                ('post_incident_actions', models.TextField(blank=True, help_text='Akcje podjęte po incydencie (naprawcze, zapobiegawcze)', verbose_name='Działania po incydencie')),
                ('conclusions', models.TextField(blank=True, verbose_name='Wnioski')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zamknięcia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('affected_assets', models.ManyToManyField(blank=True, related_name='incidents', to='assets.asset', verbose_name='Dotknięte aktywa')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='core.employee', verbose_name='Przypisany do')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszający')),
            ],
            options={
                'verbose_name': 'Incydent',
                'verbose_name_plural': 'Incydenty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Zgłoszono'), ('updated', 'Zaktualizowano'), ('status_changed', 'Zmieniono status'), ('assigned', 'Przypisano'), ('note_added', 'Dodano notatkę'), ('closed', 'Zamknięto')], max_length=20, verbose_name='Akcja')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data i czas')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incidents.incident', verbose_name='Incydent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dziennik incydentu',
                'verbose_name_plural': 'Dziennik incydentów',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('comment', 'Komentarz'), ('analysis', 'Analiza'), ('response', 'Reakcja'), ('action', 'Działanie'), ('info', 'Dodatkowe informacje')], default='comment', max_length=20, verbose_name='Typ')),
                ('content', models.TextField(verbose_name='Treść')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='incidents.incident', verbose_name='Incydent')),
            ],
            options={
                'verbose_name': 'Notatka do incydentu',
                'verbose_name_plural': 'Notatki do incydentów',
                'ordering': ['-created_at'],
            },
        ),
    ]
