# Generated by Django 5.2.8 on 2026-02-11 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_load_system_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('code', models.CharField(help_text='Krótki kod, np. HW, SW, DATA, SVC', max_length=20, unique=True, verbose_name='Kod kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.assetcategory', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Kategoria aktywów',
                'verbose_name_plural': 'Kategorie aktywów',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Unikalne oznaczenie aktywa, np. HW-001, SW-015', max_length=50, unique=True, verbose_name='Oznaczenie')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('inactive', 'Nieaktywny'), ('in_repair', 'W naprawie'), ('disposed', 'Zlikwidowany'), ('planned', 'Planowany')], default='active', max_length=20, verbose_name='Status')),
                ('criticality', models.CharField(choices=[('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka'), ('critical', 'Krytyczna')], default='medium', max_length=20, verbose_name='Krytyczność')),
                ('location', models.CharField(blank=True, help_text='Fizyczna lokalizacja aktywa (budynek, pokój, etc.)', max_length=255, verbose_name='Lokalizacja')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Data nabycia')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Data wygaśnięcia gwarancji')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Wartość (PLN)')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Numer seryjny')),
                ('inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Numer inwentarzowy')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('custodian', models.ForeignKey(blank=True, help_text='Osoba odpowiedzialna za fizyczną opiekę nad aktywem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_assets', to='core.employee', verbose_name='Opiekun')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.department', verbose_name='Dział')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Aktywo',
                'verbose_name_plural': 'Aktywa',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Utworzono'), ('updated', 'Zaktualizowano'), ('status_changed', 'Zmieniono status'), ('owner_changed', 'Zmieniono właściciela'), ('disposed', 'Zlikwidowano')], max_length=20, verbose_name='Akcja')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data i czas')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.asset', verbose_name='Aktywo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dziennik aktywów',
                'verbose_name_plural': 'Dziennik aktywów',
                'ordering': ['-timestamp'],
            },
        ),
    ]
