# Generated by Django 5.2.8 on 2026-02-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0008_load_system_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='inventory_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_assets', to='core.employee', verbose_name='Właściciel'),
        ),
    ]
