# Generated by Django 6.0 on 2026-01-02 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISORequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_id', models.CharField(help_text='Identyfikator zgodny z ISO 27001, np. A.5.1.1', max_length=20, unique=True, verbose_name='ID zabezpieczenia')),
                ('name', models.CharField(max_length=500, verbose_name='Nazwa zabezpieczenia')),
                ('description', models.TextField(blank=True, verbose_name='Opis zabezpieczenia')),
                ('is_applied', models.CharField(choices=[('yes', 'Tak'), ('no', 'Nie'), ('partial', 'Częściowo'), ('not_applicable', 'Nie dotyczy')], default='no', max_length=20, verbose_name='Czy stosujemy?')),
                ('implementation_method', models.TextField(blank=True, help_text='Opis sposobu realizacji zabezpieczenia lub odniesienie do dokumentu', verbose_name='Sposób realizacji / Dokument referencyjny')),
                ('category', models.CharField(blank=True, help_text="Kategoria zabezpieczenia, np. 'A.5 Polityki bezpieczeństwa'", max_length=100, verbose_name='Kategoria')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_iso_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_iso_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Zmodyfikował')),
            ],
            options={
                'verbose_name': 'Wymaganie ISO',
                'verbose_name_plural': 'Wymagania ISO',
                'ordering': ['iso_id'],
            },
        ),
    ]
