# Generated by Django 5.2.8 on 2026-02-10 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISODomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Np. A.5, A.6, A.7', max_length=10, unique=True, verbose_name='Kod domeny')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa domeny')),
            ],
            options={
                'verbose_name': 'Domena ISO',
                'verbose_name_plural': 'Domeny ISO',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='isorequirement',
            name='category',
        ),
        migrations.CreateModel(
            name='ISOAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='iso_attachments/%Y/%m/', verbose_name='Plik')),
                ('title', models.CharField(max_length=300, verbose_name='Tytuł / opis pliku')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dictionary.isorequirement', verbose_name='Wymaganie')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dodał')),
            ],
            options={
                'verbose_name': 'Załącznik ISO',
                'verbose_name_plural': 'Załączniki ISO',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ISOObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Np. A.5.1, A.6.1', max_length=10, unique=True, verbose_name='Kod celu')),
                ('name', models.CharField(max_length=500, verbose_name='Nazwa celu')),
                ('objective_text', models.TextField(blank=True, help_text='Treść celu opisującego dlaczego stosujemy zabezpieczenia z tej grupy', verbose_name='Cel stosowania zabezpieczeń')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='dictionary.isodomain', verbose_name='Domena')),
            ],
            options={
                'verbose_name': 'Cel zabezpieczeń ISO',
                'verbose_name_plural': 'Cele zabezpieczeń ISO',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='isorequirement',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='dictionary.isoobjective', verbose_name='Cel zabezpieczeń'),
        ),
    ]
