# Generated by Django 5.2.8 on 2026-02-10 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_add_domain_objective_attachment_remove_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isoobjective',
            options={'ordering': ['code'], 'verbose_name': 'Cel wymagań ISO', 'verbose_name_plural': 'Cele wymagań ISO'},
        ),
        migrations.AlterField(
            model_name='isoobjective',
            name='objective_text',
            field=models.TextField(blank=True, help_text='Treść celu opisującego dlaczego stosujemy wymagania z tej grupy', verbose_name='Cel stosowania wymagań'),
        ),
        migrations.AlterField(
            model_name='isorequirement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis wymagania'),
        ),
        migrations.AlterField(
            model_name='isorequirement',
            name='implementation_method',
            field=models.TextField(blank=True, help_text='Opis sposobu realizacji wymagania lub odniesienie do dokumentu', verbose_name='Sposób realizacji / Dokument referencyjny'),
        ),
        migrations.AlterField(
            model_name='isorequirement',
            name='iso_id',
            field=models.CharField(help_text='Identyfikator zgodny z ISO 27001, np. A.5.1.1', max_length=20, unique=True, verbose_name='ID wymagania'),
        ),
        migrations.AlterField(
            model_name='isorequirement',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nazwa wymagania'),
        ),
        migrations.AlterField(
            model_name='isorequirement',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='dictionary.isoobjective', verbose_name='Cel wymagań'),
        ),
    ]
