# Generated by Django 5.2.8 on 2026-02-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_rename_zabezpieczenie_to_wymaganie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Np. A, B, C, D', max_length=5, unique=True, verbose_name='Kod kategorii')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, help_text='Opcjonalny opis głównej kategorii', verbose_name='Opis kategorii')),
            ],
            options={
                'verbose_name': 'Kategoria ISO',
                'verbose_name_plural': 'Kategorie ISO',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='isodomain',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Główna kategoria nadrzędna (A, B, C, D)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='dictionary.isocategory', verbose_name='Kategoria'),
        ),
    ]
