# Generated by Django 5.2.8 on 2026-02-11 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_load_system_permissions'),
        ('dictionary', '0003_rename_zabezpieczenie_to_wymaganie'),
        ('documents', '0004_alter_documentaccess_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoADeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Unikalne oznaczenie deklaracji, np. SOA-001', max_length=50, unique=True, verbose_name='Oznaczenie')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Wersja')),
                ('status', models.CharField(choices=[('draft', 'Wersja robocza'), ('review', 'W przeglądzie'), ('approved', 'Zatwierdzona'), ('current', 'Obowiązująca'), ('archived', 'Zarchiwizowana')], default='draft', max_length=20, verbose_name='Status')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Data obowiązywania')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_soa_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_soa_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Deklaracja Stosowania',
                'verbose_name_plural': 'Deklaracje Stosowania',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SoALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Utworzono'), ('updated', 'Zaktualizowano'), ('status_changed', 'Zmieniono status'), ('entry_added', 'Dodano pozycję'), ('entry_updated', 'Zaktualizowano pozycję'), ('entry_removed', 'Usunięto pozycję')], max_length=20, verbose_name='Akcja')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data i czas')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='soa.soadeclaration', verbose_name='Deklaracja')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dziennik Deklaracji Stosowania',
                'verbose_name_plural': 'Dziennik Deklaracji Stosowania',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SoAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicability', models.CharField(choices=[('yes', 'Tak - stosowane'), ('no', 'Nie - niestosowane'), ('partial', 'Częściowo stosowane'), ('not_applicable', 'Nie dotyczy')], default='yes', max_length=20, verbose_name='Stosowanie')),
                ('justification', models.TextField(help_text='Uzasadnienie stosowania lub niestosowania wymagania', verbose_name='Uzasadnienie')),
                ('additional_description', models.TextField(blank=True, verbose_name='Dodatkowy opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='soa.soadeclaration', verbose_name='Deklaracja')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='soa_entries', to='documents.document', verbose_name='Powiązane dokumenty')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soa_entries', to='dictionary.isorequirement', verbose_name='Wymaganie ISO')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soa_responsibilities', to='core.employee', verbose_name='Osoba odpowiedzialna')),
            ],
            options={
                'verbose_name': 'Pozycja Deklaracji Stosowania',
                'verbose_name_plural': 'Pozycje Deklaracji Stosowania',
                'ordering': ['requirement__iso_id'],
                'unique_together': {('declaration', 'requirement')},
            },
        ),
    ]
