# Generated by Django 5.2.8 on 2025-12-12 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Kod uprawnienia')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa uprawnienia')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('category', models.CharField(choices=[('documents', 'Dokumenty'), ('assets', 'Aktywa'), ('incidents', 'Incydenty'), ('audits', 'Audyty'), ('organization', 'Organizacja'), ('system', 'System')], default='system', max_length=50, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Uprawnienie',
                'verbose_name_plural': 'Uprawnienia',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa grupy')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups', to='core.permission', verbose_name='Uprawnienia')),
            ],
            options={
                'verbose_name': 'Grupa uprawnień',
                'verbose_name_plural': 'Grupy uprawnień',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przypisania')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_assignments', to='core.department', verbose_name='Dział')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='core.permissiongroup', verbose_name='Grupa uprawnień')),
            ],
            options={
                'verbose_name': 'Uprawnienie działu',
                'verbose_name_plural': 'Uprawnienia działów',
                'unique_together': {('department', 'permission_group')},
            },
        ),
        migrations.CreateModel(
            name='PositionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przypisania')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='core.permissiongroup', verbose_name='Grupa uprawnień')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_assignments', to='core.position', verbose_name='Stanowisko')),
            ],
            options={
                'verbose_name': 'Uprawnienie stanowiska',
                'verbose_name_plural': 'Uprawnienia stanowisk',
                'unique_together': {('position', 'permission_group')},
            },
        ),
    ]
