# Generated by Django 5.2.8 on 2025-12-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permission_permissiongroup_departmentpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='code',
        ),
    ]
