# Generated by Django 5.2.8 on 2025-12-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employee_email_remove_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.position', verbose_name='Stanowiska'),
        ),
        migrations.CreateModel(
            name='EmployeePermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przypisania')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_group_assignments', to='core.employee', verbose_name='Pracownik')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='core.permissiongroup', verbose_name='Grupa uprawnień')),
            ],
            options={
                'verbose_name': 'Grupa uprawnień pracownika',
                'verbose_name_plural': 'Grupy uprawnień pracowników',
                'unique_together': {('employee', 'permission_group')},
            },
        ),
    ]
