# Generated by Django 6.0 on 2025-12-17 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_employee_position_employee_positions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Utworzenie'), ('update', 'Modyfikacja'), ('delete', 'Usunięcie'), ('assign', 'Przypisanie'), ('unassign', 'Cofnięcie przypisania'), ('login', 'Logowanie'), ('logout', 'Wylogowanie'), ('view', 'Wyświetlenie'), ('export', 'Eksport'), ('import', 'Import'), ('other', 'Inne')], max_length=20, verbose_name='Akcja')),
                ('category', models.CharField(choices=[('organization', 'Organizacja'), ('department', 'Dział'), ('position', 'Stanowisko'), ('employee', 'Pracownik'), ('permission', 'Uprawnienia'), ('document', 'Dokument'), ('asset', 'Aktywo'), ('incident', 'Incydent'), ('audit', 'Audyt'), ('system', 'System'), ('auth', 'Autoryzacja')], max_length=20, verbose_name='Kategoria')),
                ('object_type', models.CharField(help_text="Nazwa modelu, np. 'Employee', 'Department'", max_length=100, verbose_name='Typ obiektu')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID obiektu')),
                ('object_repr', models.CharField(help_text='Tekstowa reprezentacja obiektu, np. nazwa pracownika', max_length=255, verbose_name='Reprezentacja obiektu')),
                ('description', models.TextField(verbose_name='Opis zdarzenia')),
                ('details', models.JSONField(blank=True, help_text='Dodatkowe informacje w formacie JSON', null=True, verbose_name='Szczegóły')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zdarzenia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Zdarzenie',
                'verbose_name_plural': 'Dziennik zdarzeń',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx'), models.Index(fields=['category', '-created_at'], name='core_activi_categor_969ef1_idx'), models.Index(fields=['action', '-created_at'], name='core_activi_action_a01617_idx')],
            },
        ),
    ]
