# Generated by Django 6.0 on 2026-01-02 20:59

from django.db import migrations, models


def load_permissions(apps, schema_editor):
    """Ładuje predefiniowane uprawnienia do bazy danych"""
    Permission = apps.get_model('core', 'Permission')
    
    PERMISSIONS = [
        # AUDYTY
        ('audits', 'Administrator audytów', 'Przeglądanie wszystkich audytów i zarządzanie właścicielami audytów'),
        ('audits', 'Przeglądający audyty', 'Przeglądanie wszystkich audytów bez możliwości edycji'),
        ('audits', 'Właściciel audytów', 'Dostęp do wszystkich audytów, wypełnianie danych i zmiany statusów'),
        ('audits', 'Menedżer audytów', 'Dostęp do wszystkich audytów i wypełnianie danych bez zmiany statusów'),
        
        # DEKLARACJE ZGODNOŚCI
        ('compliance', 'Administrator deklaracji zgodności', 'Przeglądanie wszystkich deklaracji zgodności i zmiana ich właścicieli'),
        ('compliance', 'Właściciel deklaracji zgodności', 'Pełne uprawnienia do tworzenia, edycji i zarządzania cyklem życia deklaracji zgodności'),
        ('compliance', 'Menedżer deklaracji zgodności', 'Zarządzanie przypisanymi deklaracjami zgodności - edycja, aktualizacja statusu i przesyłanie do zatwierdzenia'),
        ('compliance', 'Zatwierdzający deklaracje zgodności', 'Uprawnienia do zatwierdzania i odrzucania deklaracji zgodności przesyłanych do akceptacji'),
        
        # DOKUMENTY
        ('documents', 'Administrator dokumentów', 'Przeglądanie wszystkich dokumentów i zmiana ich właścicieli'),
        ('documents', 'Właściciel dokumentów', 'Pełne uprawnienia do tworzenia, edycji, usuwania i zarządzania cyklem życia dokumentów'),
        ('documents', 'Menedżer dokumentów', 'Zarządzanie przypisanymi dokumentami, edycja, aktualizacja statusu i przesyłanie do zatwierdzenia'),
        ('documents', 'Zatwierdzający dokumenty', 'Uprawnienia do zatwierdzania i odrzucania dokumentów przesyłanych do akceptacji'),
        ('documents', 'Podpisujący dokumenty', 'Uprawnienia do podpisywania dokumentów'),
        ('documents', 'Weryfikujący podpisy elektroniczne', 'Uprawnienia do weryfikacji podpisów elektronicznych w module dokumentów'),
        
        # DZIENNIK ZDARZEŃ
        ('activity_log', 'Przeglądanie dziennika zdarzeń', 'Przeglądanie wszystkich zdarzeń w rejestrze'),
        
        # INCYDENTY BEZPIECZEŃSTWA
        ('incidents', 'Przeglądanie wszystkich incydentów bezpieczeństwa', 'Dostęp do przeglądania wszystkich incydentów bezpieczeństwa bez możliwości ich edycji'),
        ('incidents', 'Przeglądanie moich incydentów bezpieczeństwa', 'Dostęp do przeglądania incydentów bezpieczeństwa, które zostały przez mnie zgłoszone'),
        ('incidents', 'Administrator incydentów bezpieczeństwa', 'Przeglądanie wszystkich incydentów bezpieczeństwa i zmiana ich właścicieli'),
        ('incidents', 'Zarządzanie przypisanymi incydentami bezpieczeństwa', 'Pełne zarządzanie incydentami bezpieczeństwa, do których jestem przypisany jako właściciel lub menedżer'),
        
        # KONFIGURACJA
        ('configuration', 'Zarządzanie konfiguracją', 'Pozwala na zarządzanie konfiguracją systemową'),
        
        # REJESTR AKTYWÓW
        ('assets', 'Administrator rejestru aktywów', 'Przeglądanie wszystkich aktywów i zmiana ich właścicieli, tworzenie grup aktywów'),
        ('assets', 'Właściciel rejestru aktywów', 'Pełne uprawnienia do tworzenia, edycji, usuwania i zarządzania aktywami w rejestrze'),
        ('assets', 'Przeglądanie rejestru aktywów', 'Przeglądanie wszystkich aktywów w rejestrze bez możliwości edycji'),
        
        # WYMAGANIA STANDARDÓW I PRZEPISÓW
        ('dictionary', 'Zarządzanie słownikami wymagań norm i przepisów', 'Pełne uprawnienia do tworzenia, edycji i usuwania słowników wymagań norm i przepisów'),
        
        # LOGI
        ('logs', 'Zarządzanie usuwaniem logów', 'Pozwala na natychmiastowe usuwanie oznaczonych logów'),
        
        # PODMIOTY / ORGANIZACJA
        ('organization', 'Zarządzanie organizacją', 'Pozwala na pełne zarządzanie strukturą organizacji'),
        ('organization', 'Zarządzanie jednostką', 'Pozwala na zarządzanie jedną jednostką organizacyjną'),
        
        # UŻYTKOWNICY
        ('users', 'Zarządzanie użytkownikami', 'Pozwala na dodawanie, edycję i usuwanie użytkowników'),
        
        # UPRAWNIENIA
        ('permissions', 'Zarządzanie uprawnieniami', 'Pozwala na zarządzanie uprawnieniami i przypisywanie ich do ról'),
    ]
    
    for category, name, description in PERMISSIONS:
        Permission.objects.update_or_create(
            name=name,
            defaults={
                'category': category,
                'description': description,
                'is_system': True,
            }
        )


def remove_permissions(apps, schema_editor):
    """Usuwa predefiniowane uprawnienia (reverse migration)"""
    Permission = apps.get_model('core', 'Permission')
    Permission.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_system',
            field=models.BooleanField(default=True, help_text='Uprawnienia systemowe są predefiniowane i nie można ich usunąć', verbose_name='Uprawnienie systemowe'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('audits', 'Audyty'), ('compliance', 'Deklaracje zgodności'), ('documents', 'Dokumenty'), ('activity_log', 'Dziennik zdarzeń'), ('incidents', 'Incydenty bezpieczeństwa'), ('configuration', 'Konfiguracja'), ('assets', 'Rejestr aktywów'), ('dictionary', 'Wymagania standardów i przepisów'), ('logs', 'Logi'), ('organization', 'Podmioty / Organizacja'), ('users', 'Użytkownicy'), ('permissions', 'Uprawnienia')], default='configuration', max_length=50, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa uprawnienia'),
        ),
        migrations.RunPython(load_permissions, remove_permissions),
    ]
